-- 1. Cocktail Name

insert into Cocktail_Name(cocktail_name) 
values 
	('ALEXANDER'),
	('AMERICANO'),
	('ANGEL FACE'),
	('AVIATION'),
	('B52'),
	('BACARDI'),
	('BARRACUDA'),
	('BELLINI'),
	('BETWEEN THE SHEETS'),
	('BLACK RUSSIAN'),
	('WHITE RUSSIAN'),
	('BLOODY MARY'),
	('BRAMBLE');

-- 2. Ingredients
insert into ingredients(ingredient_name) 
values
	('Absinthe'),
	('Agave nectar'),
	('Angostura Bitters'),
	('Aperol'),
	('Apricot Brandy'),
	('Bacardi Rum White'),
	('Bailey''s Irish Cream'),
	('Bourbon or Rye whiskey'),
	('Bourbon whiskey'),
	('Brandy'),
	('brown sugar'),
	('Calvados'),
	('Campari'),
	('Celery salt'),
	('Champagne'),
	('Cherry liqueur'),
	('Chilled Champagne'),
	('Citron Vodka'),
	('clear honey'),
	('Coconut milk'),
	('Coffee liqueur'),
	('cognac'),
	('Cointreau'),
	('Cola'),
	('Cranberry juice'),
	('Cream'),
	('creme de Cacao'),
	('Creme de cacao (white)'),
	('Creme de Cassis'),
	('Creme de menthe (green)'),
	('Creme de Menthe (white)'),
	('Dark Rum'),
	('Dashes Angostura Bitters'),
	('DiSaronno'),
	('DOM Benedictine'),
	('Drambuie'),
	('Dry Vermouth'),
	('Dry White Wine'),
	('Egg White'),
	('Egg yolk'),
	('Fresh red hot chili peppers'),
	('Fresh Cream'),
	('Fresh lemon juice'),
	('Fresh lime'),
	('Fresh lime juice'),
	('Fresh mint leaves'),
	('Fresh Orange juice'),
	('Fresh peach puree'),
	('Fresh pineapple juice'),
	('Galliano'),
	('Gin'),
	('Ginger Ale'),
	('Ginger Beer'),
	('Gold rum'),
	('Gomme syrup'),
	('Grand Marnier (Flame, serve while burning)'),
	('Grapefruit juice'),
	('Grenadine'),
	('Grenadine syrup'),
	('Hot coffee'),
	('Irish whiskey (heat up)'),
	('Kahlua'),
	('Kirsch'),
	('Lemon Juice'),
	('Lillet Blonde'),
	('Lime juice'),
	('Maraschino'),
	('Mint'),
	('Old Tom Gin'),
	('Olive juice'),
	('onion finely chopped'),
	('Orange Bitters'),
	('Orange Curacao'),
	('Orange flower water'),
	('Orange juice'),
	('Orgeat syrup'),
	('Peach Bitters'),
	('Peach schnapps'),
	('Pepper'),
	('Peychaud''s bitters'),
	('Pineapple juice'),
	('Pisco'),
	('powdered sugar'),
	('Prosecco'),
	('Raspberry liqueur'),
	('Raspberry syrup'),
	('Red Port'),
	('red vermouth'),
	('Rye Whiskey'),
	('Salt'),
	('Scotch whiskey'),
	('Simple syrup'),
	('Soda water'),
	('Strawberry syrup'),
	('strong Espresso'),
	('sugar cube'),
	('Sugar syrup'),
	('Sweet Red Vermouth'),
	('Tabasco'),
	('Tequila'),
	('Tequila (silver)'),
	('Tomato juice'),
	('Triple Sec'),
	('Vanilla extract'),
	('Vodka'),
	('Vodka Citron'),
	('water'),
	('White Cuban Rum'),
	('White Rum'),
	('white sugar'),
	('Worcestershire Sauce');

-- 3. Measurements
insert into measurements(measurement_name) 
values 
	('Bar spoon'),
	('cl'),
	('Dash(s)'),
	('drops'),
	('Parts'),
	('Slice'),
	('Small'),
	('Splash'),
	('Sprigs'),
	('Sprinkle'),
	('Teaspoon(s)'),
	('top with'),
	('Short'),
	('Wedges'),
	('Rinse glass and discard');

-- 4. Method
insert into method(method_name) 
values 
	('blend'),
	('Disolve sugar with bitters and water,add rest.'),
	('dry shake, hard shake & strain'),
	('Float fresh cream on the top and stir gently'),
	('Layer ingredients'),
	('mix with ice'),
	('muddle'),
	('muddle lime, sugar and mint'),
	('muddle the mint, sugar and water. stir'),
	('pour'),
	('pour (build)'),
	('pour, do not stir'),
	('Shake'),
	('shake & strain'),
	('stir'),
	('Stir & strain'),
	('Stir gently'),
	('warm & pour');

-- 5. Garnish
insert into garnish(garnish_name) 
values 
	('blackberry'),
	('celery'),
	('Cherry'),
	('chili'),
	('cocktail cherry'),
	('freshly ground nutmeg'),
	('fresh mint leaves'),
	('green olive'),
	('half orange slice'),
	('Lemon peel'),
	('Lemon slice'),
	('lemon spiral'),
	('lemon twist'),
	('Lemon wedge'),
	('lemon zest twist'),
	('lime peel'),
	('lime slice'),
	('lime wedge'),
	('maraschino cherry'),
	('mint leaves'),
	('mint sprig'),
	('Nutmeg'),
	('olive'),
	('orange Slice'),
	('orange twist'),
	('pineapple spear'),
	('pineapple slice'),
	('rind of one lemon spiral'),
	('Squeeze oil from lemon peel'),
	('two blackberries');

-- 6. Top_Up
insert into top_up(top_up_name)
values
	('Angostura Bitters (add on sugar cube)'),
	('Blackberry liqueur'),
	('Cachaca'),
	('Champagne'),
	('Dash of Angostura bitters'),
	('Galliano to float on drink'),
	('Grenadine'),
	('Oil from lemon peel'),
	('Rim glass with Salt'),
	('Rim glass with Sugar'),
	('Serve with straw'),
	('Soda water'),
	('Sparkling wine'),
	('Straw on side plate'),
	('Prosecco');
    
-- 7. Drink_Type
insert into drink_type(drink_type_name)
values
	('After Dinner Cocktail'),
	('All Day Cocktail'),
	('Before Dinner Cocktail'),
	('Hot Drink'),
	('Longdrink'),
	('Sparkling Cocktail');
    
-- 8. Glass_Type
insert into glass_type(glass_type_name)
values
	('champagne flute'),
	('champagne glass'),
	('cocktail'),
	('double cocktail'),
	('flute'),
	('highball'),
	('Large cocktail glass'),
	('large glass'),
	('large goblet'),
	('martini glass'),
	('old-fashioned'),
	('rock'),
	('tumbler'),
	('wine glass');
    
-- 9. cocktail_details

insert into cocktail_details(
	CD_cocktail_name_ID,
    CD_drink_type_ID,
    CD_method_ID,
    CD_glass_type_ID,
    CD_top_up_ID)
values
	(1, 1, 12, 3, null),
    (2, 3, 6, 11, null),
    (3, 2, 14, 3, null),
    (4, 2, 14, 3, null),
    (5, 1, 5, null, 14),
    (6, 3, 14, 3, null),
    (7, 6, null, 3, 15),
    (8, 6, 15, 14, null),
    (9, 2, 14, 3, null),
    (10, 1, 15, 11, null),
    (11, 1, 4, 11, null),
    (12, 5, 15, 6, null),
    (13, 2, 15, 12,2);
    
    -- 10. cocktail_garnish
    
insert into cocktail_garnish(
	CG_cocktail_name_ID,
    CG_garnish_ID)
values
	(1, 22),
    (2, 9),
    (4, 10),
    (4, 10),
    (12, 2),
    (12, 14),
    (13, 11),
    (13, 30);
    
-- 11. cocktail_recipe
    
insert into cocktail_recipe(
	CR_cocktail_name_ID,
    Quantity,
    CR_measurement_ID,
    CR_ingredient_ID)
values
	(1,	3,	5,	22),
	(1,	3,	5,	27),
	(1,	3,	5,	42),
	(2,	3,	5,	13),
	(2,	3,	5,	88),
	(2,	1,	5,	93),
	(3,	3,	5,	51),
	(3,	3,	5,	5),
	(3,	3,	5,	12),
	(4,	4.5, 5,	51),
	(4,	1.5, 5,	67),
	(4,	1.5, 5,	64),
	(5,	2,	2,	62),
	(5,	2,	2,	7),
	(5,	2,	2,	56),
	(6,	4.5, 5,	6),
	(6,	2,	5,	45),
	(6,	1,	5,	58),
	(7,	4.5, 2,	54),
	(7,	1.5, 2,	50),
	(7,	6,	2,	81),
	(7,	1,	3,	45),
	(8,	10,	5,	84),
	(8,	5,	5,	48),
	(9,	3,	5,	109),
	(9,	3,	5,	22),
	(9,	3,	5,	103),
	(9,	2,	5,	43),
	(10, 5,	5,	105),
	(10, 2,	5,	21),
	(11, 5,	5,	105),
	(11, 2,	5,	21),
	(11, 1,	5,	42),
	(12, 4.5, 5, 105),
	(12, 9,	5,	102),
	(12, 1.5, 5, 64),
	(12, 2.5, 3, 111),
	(12, 1,	10,	99),
	(12, 1,	10,	14),
	(12, 1,	10,	79),
	(13, 4,	2,	51),
	(13, 1.5, 2, 43),
	(13, 1,	2, 97);
    
-- 12. City_or_State
insert into city_or_state(city_or_state_name) 
values 
	('Alentejo'),
	('Arizona'),
	('Brussels'),
	('California'),
	('Chicago'),
	('Florence'),
	('Florida'),
	('Havana'),
	('Kentucky'),
	('Lima'),
	('London'),
	('Louisiana'),
	('Milan'),
	('New Orleans'),
	('New York'),
	('Paris'),
	('Persian Gulf'),
	('San Juan'),
	('Venice'),
	('Washington');
    
-- 13. City_or_State
insert into country(country_name) 
values 
	('Belgium'),
	('Bermuda'),
	('Chile'),
	('Cuba'),
	('England'),
	('France'),
	('Italy'),
	('Jamaica'),
	('Mexico'),
	('Open Seas'),
	('Peru'),
	('Portugal'),
	('Puerto Rico'),
	('Singapore'),
	('USA');
    
-- 14. person_or_bar
insert into person_or_bar(person_or_bar_name) 
values 
	('Gaspare Campari''s bar'),
	('Savoy Cocktail Book compiled by Harry Craddock'),
	('Hugo Ensslin'),
	('Alice''s restaurant in Malibu'),
	('Jacques Straub'),
	('Benito Cuppari'),
	('Giuseppe Cipriani'),
	('Harry''s New York Bar'),
	('Gustav Tops'),
	('Dick Bradsell');
    
-- 15. Cocktail_Origin
insert into cocktail_origin(
	CO_cocktail_name_ID,
    CO_city_or_state_ID,
    CO_country_ID,
    CO_person_or_bar_ID,
    year_created)
values
	(1,	null, null, null, 1901),
	(2,	13,	7, 1, 1860),
	(3,	null, null,	2, 1930),
	(4,	15,	15,	3,	1901),
	(5,	4,	15,	4,1960),
	(6,	5,	15,	5, 1914),
	(7,	null, 10, 6,	1950),
	(8,	19,	7, 7, 1934),
	(9,	16,	6, 8, 1930),
	(10, 3,	1, 9,	1949),
	(11, 4,	15, null, 1960),
	(12, 16, 6,	8, 1921),
	(13, 11, 5,	10, 1984);
	